const theme = {
    colors: {
      background: 'var(--black)',
      backgroundLight: 'var(--black-light)',
      backgroundLighter: 'var(--black-lighter)',
      text: 'var(--white)',
      textMuted: 'var(--gray-light)',
      primary: 'var(--orange-primary)',
      primaryLight: 'var(--orange-light)',
      primaryNeon: 'var(--orange-neon)',
      primaryDark: 'var(--orange-dark)',
      gray: 'var(--gray)',
      grayDark: 'var(--gray-dark)',
      grayLight: 'var(--gray-light)',
      success: 'var(--success)',
      warning: 'var(--warning)',
      error: 'var(--error)',
    },
    fonts: {
      body: 'var(--font-sans)',
      heading: 'var(--font-heading)',
    },
    fontSizes: {
      xs: '0.75rem',
      sm: '0.875rem',
      md: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '3.75rem',
    },
    shadows: {
      sm: 'var(--shadow-sm)',
      md: 'var(--shadow-md)',
      lg: 'var(--shadow-lg)',
      glow: 'var(--glow-orange)',
      glowStrong: 'var(--glow-orange-strong)',
    },
    radii: {
      sm: 'var(--radius-sm)',
      md: 'var(--radius-md)',
      lg: 'var(--radius-lg)',
      full: '9999px',
    },
    transitions: {
      fast: 'var(--transition-fast)',
      normal: 'var(--transition-normal)',
      slow: 'var(--transition-slow)',
    },
    breakpoints: {
      xs: '320px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    spacing: {
      0: '0',
      1: '0.25rem',
      2: '0.5rem',
      3: '0.75rem',
      4: '1rem',
      5: '1.25rem',
      6: '1.5rem',
      8: '2rem',
      10: '2.5rem',
      12: '3rem',
      16: '4rem',
      20: '5rem',
      24: '6rem',
      32: '8rem',
      40: '10rem',
      48: '12rem',
      56: '14rem',
      64: '16rem',
    },
    zIndices: {
      base: 0,
      dropdown: 1000,
      sticky: 1100,
      fixed: 1200,
      modal: 1300,
      popover: 1400,
      toast: 1500,
      tooltip: 1600,
    },
  }
  
  export default theme